name: rent-a-drone
favicon: null
layout_spectrum: 0.1937948316335678
typography_spectrum: 0.10117458598688245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6561749815009534
  lightness: 0.2903362666256726
  saturation: 0.3643999779596925
  rhythmicContrast: 0.6733825642149895
purpose: []
